### PR TITLE
Top5

### PR DESCRIPTION
**Pull request by Mr-Darfler**
This PR address #10

### CODE REVIEW

**Review by pryan4 — APPROVED** [review]

**Review by BLehrer99 — CHANGES_REQUESTED** [review]
I like it but I'm not too sure about birthday cake. Maybe we should remove that one.

**Review by BLehrer99 — APPROVED** [review]

**Review by gordoniii — APPROVED** [review]

**Review by BLehrer99 — APPROVED** [review]
I approve

**Review by awualex — APPROVED** [review]

**Review by Jkohl1 — COMMENTED** [review]
nice

**Comment by Mr-Darfler** [comment]
Great work. This closes #10

**Pull request merged**
